/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sew9.worttrainer.jschulz04;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WorttrainerTest {
    @Test void test() {
        System.out.println("GEHT");
    }
}
